import type { ActionGraphProjection, ProofPacket } from "./types";

export const sampleProjection: ActionGraphProjection = {
  schema_version: 1,
  projection_kind: "action_graph",
  generated_at: "2026-06-06T00:00:00.000000Z",
  run_group: "latest",
  summary: {
    runs: 1,
    nodes: 8,
    edges: 7,
    cache_events: 2,
    failures: 1,
    target_statuses: {
      PASSED: 1,
      FAILED: 1,
    },
  },
  nodes: [
    {
      id: "run-fixture",
      kind: "run",
      label: "agent-loop cache-only",
      status: "ingested",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
      payload: { mode: "cache-only" },
    },
    {
      id: "target-priority",
      kind: "target",
      label: "//tasks:priority_test",
      status: "PASSED",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "target-flaky",
      kind: "target",
      label: "//tasks:flaky_test",
      status: "FAILED",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "action-priority",
      kind: "action",
      label: "PyTest priority",
      status: "PASSED",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "cache-hit",
      kind: "cache_event",
      label: "remote cache hit",
      status: "remote_cache_hit",
      source_kind: "derived_v1",
      confidence: "medium",
      evidence_refs: ["fixture:execution-log.json"],
      redaction_state: "safe",
    },
    {
      id: "cache-miss",
      kind: "cache_event",
      label: "cache miss",
      status: "cache_miss",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:execution-log.json"],
      redaction_state: "safe",
    },
    {
      id: "failure-flaky",
      kind: "failure",
      label: "flaky ordering failure",
      status: "FAILED",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "artifact-run",
      kind: "artifact",
      label: "proof packet",
      status: "safe",
      source_kind: "collectable_v1",
      confidence: "high",
      evidence_refs: ["manifest:run"],
      redaction_state: "safe",
    },
  ],
  edges: [
    {
      id: "run-target-priority",
      from: "run-fixture",
      to: "target-priority",
      kind: "evaluated_target",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "run-target-flaky",
      from: "run-fixture",
      to: "target-flaky",
      kind: "evaluated_target",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "target-action-priority",
      from: "target-priority",
      to: "action-priority",
      kind: "produced_action",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "action-cache-hit",
      from: "action-priority",
      to: "cache-hit",
      kind: "observed_cache_event",
      source_kind: "derived_v1",
      confidence: "medium",
      evidence_refs: ["fixture:execution-log.json"],
      redaction_state: "safe",
    },
    {
      id: "target-cache-miss",
      from: "target-flaky",
      to: "cache-miss",
      kind: "observed_cache_event",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:execution-log.json"],
      redaction_state: "safe",
    },
    {
      id: "target-failure",
      from: "target-flaky",
      to: "failure-flaky",
      kind: "observed_failure",
      source_kind: "simulated_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
    {
      id: "run-artifact",
      from: "run-fixture",
      to: "artifact-run",
      kind: "recorded_artifact",
      source_kind: "collectable_v1",
      confidence: "high",
      evidence_refs: ["manifest:run"],
      redaction_state: "safe",
    },
  ],
};

export const sampleProofPacket: ProofPacket = {
  schema_version: 1,
  projection_kind: "proof_packet",
  generated_at: "2026-06-06T00:00:00.000000Z",
  run_group: "latest",
  summary: {
    runs: 1,
    artifacts: 1,
    targets: 2,
    actions: 3,
    cache_events: 2,
    failures: 1,
  },
  blocks: [
    {
      id: "scope",
      kind: "derived_summary",
      title: "Proof Scope",
      summary: "Local cache-only evidence for AI-generated code validation.",
      claims: [
        "This packet can prove recorded commands, artifacts, statuses, and cache events present in the local evidence spine.",
        "This packet does not claim remote worker assignment, queue timing, or opaque SaaS telemetry.",
      ],
      metrics: {},
      source_kind: "derived_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl", "fixture:execution-log.json"],
      redaction_state: "safe",
    },
    {
      id: "cache",
      kind: "derived_summary",
      title: "Cache Evidence",
      summary: "Cache hit/miss records extracted from available Bazel evidence.",
      claims: [],
      metrics: {
        hits: 1,
        misses: 1,
        unknown: 0,
        hit_rate: 0.5,
      },
      source_kind: "derived_v1",
      confidence: "medium",
      evidence_refs: ["fixture:execution-log.json"],
      redaction_state: "safe",
    },
    {
      id: "validation",
      kind: "derived_summary",
      title: "Validation Surface",
      summary: "Targets, actions, and failures visible to the recorder.",
      claims: [],
      metrics: {
        targets: 2,
        actions: 3,
        failures: 1,
      },
      source_kind: "derived_v1",
      confidence: "high",
      evidence_refs: ["fixture:bep.jsonl"],
      redaction_state: "safe",
    },
  ],
};
