import type { ViewSpec } from "./types";

/** Bundled nlfr-default-v0 — equivalent to current App.tsx layout (routing.md matrix). */
export const DEFAULT_VIEW_SPEC: ViewSpec = {
  schema_version: "nlfr.view-spec.v1",
  view_id: "nlfr-default-v0",
  title: "NLFR Default Canvas",
  description: "Equivalent to current App.tsx behavior",
  generated_at: "2026-06-06T00:00:00.000Z",
  run_group: "latest",
  source_kind: "simulated_v1",
  confidence: "high",
  evidence_refs: ["view-spec:nlfr-default-v0"],
  redaction_state: "safe",
  layout: {
    kind: "grid_shell_v1",
    columns: "minmax(0,1fr) 440px",
    rows: "auto auto minmax(0,1fr) auto",
    regions: {
      notice: { grid_area: "notice", slot: "banner" },
      header: { grid_area: "header", slot: "topbar" },
      primary: { grid_area: "primary", slot: "canvas" },
      rail: { grid_area: "rail", slot: "inspector", width_px: 440 },
      operator: { grid_area: "operator", slot: "command" },
    },
    responsive: {
      breakpoint_px: 720,
      collapse_rail: "bottom_sheet",
    },
  },
  bindings: {
    "binding.action_graph": {
      projection_kind: "action_graph",
      path: "/projections/action-graph.json",
      required: true,
      fallback: "fixture:sampleProjection",
      refresh: "on_run_group_change",
    },
    "binding.proof_packet": {
      projection_kind: "proof_packet",
      path: "/projections/proof.json",
      required: true,
      fallback: "fixture:sampleProofPacket",
      refresh: "on_run_group_change",
    },
    "binding.compare": {
      projection_kind: "compare",
      path: "/projections/compare-projection.json",
      required: false,
      fallback: "none",
      refresh: "on_run_group_change",
      notes: "Optional pairwise compare; empty state when absent.",
    },
  },
  modes: [
    {
      mode_id: "graph",
      label: "Action Graph",
      icon: "git-branch",
      primary_component: "graph-main",
      rail_component: "inspector-selected-node",
      default_focus: "all",
      data_testid: "canvas-mode-graph",
    },
    {
      mode_id: "runway",
      label: "Validation Runway",
      icon: "route",
      primary_component: "graph-main",
      rail_component: "runway-overlay",
      default_focus: "all",
      data_testid: "canvas-mode-runway",
    },
    {
      mode_id: "proof",
      label: "Proof Packet",
      icon: "file-check-2",
      primary_component: "graph-main",
      rail_component: "proof-drawer",
      default_focus: "all",
      requires_binding: "binding.proof_packet",
      data_testid: "canvas-mode-proof",
    },
    {
      mode_id: "remote",
      label: "Remote Boundary",
      icon: "network",
      primary_component: "graph-main",
      rail_component: "remote-lens",
      default_focus: "remote",
      requires_binding: "binding.proof_packet",
      data_testid: "canvas-mode-remote",
    },
    {
      mode_id: "compare",
      label: "Compare Runs",
      icon: "git-compare",
      primary_component: "graph-main",
      rail_component: "compare-lens",
      default_focus: "derived",
      data_testid: "canvas-mode-compare",
    },
  ],
  components: [
    {
      instance_id: "notice",
      component_kind: "projection_notice",
      region: "notice",
      projection_binding: "binding.action_graph",
      data_testid: "projection-notice",
    },
    {
      instance_id: "topbar",
      component_kind: "topbar_summary",
      region: "header",
      projection_binding: "binding.action_graph",
      data_testid: "topbar-summary",
    },
    {
      instance_id: "modes",
      component_kind: "mode_rail",
      region: "header",
      props: { modes: "graph,runway,proof,remote,compare" },
      data_testid: "canvas-mode-rail",
    },
    {
      instance_id: "zoom",
      component_kind: "zoom_controls",
      region: "header",
      props: { target_instance_id: "graph-main" },
      visible_when: { prop_truthy: "zoom_controls" },
      data_testid: "zoom-controls",
    },
    {
      instance_id: "graph-main",
      component_kind: "action_graph_canvas",
      region: "primary",
      projection_binding: "binding.action_graph",
      props: { show_truth_legend: true, zoom_controls: true },
      data_testid: "action-graph-svg",
    },
    {
      instance_id: "legend",
      component_kind: "truth_legend",
      region: "primary",
      visible_when: { prop_truthy: "show_truth_legend" },
      data_testid: "truth-legend",
    },
    {
      instance_id: "runway-overlay",
      component_kind: "validation_runway",
      region: "primary",
      projection_binding: "binding.action_graph",
      visible_when: { mode: ["runway"] },
      data_testid: "validation-runway",
    },
    {
      instance_id: "proof-constellation",
      component_kind: "proof_constellation",
      region: "primary",
      projection_binding: "binding.proof_packet",
      visible_when: { mode: ["proof"] },
      data_testid: "proof-constellation",
    },
    {
      instance_id: "proof-drawer",
      component_kind: "proof_drawer",
      region: "rail",
      projection_binding: "binding.proof_packet",
      visible_when: { mode: ["proof"] },
      data_testid: "proof-drawer",
    },
    {
      instance_id: "remote-lens",
      component_kind: "remote_boundary_lens",
      region: "rail",
      projection_binding: {
        kind: "join_v1",
        sources: ["binding.action_graph", "binding.proof_packet"],
        join_fn: "remote_lens_model",
        source_kind: "derived_v1",
        confidence: "medium",
        evidence_refs: ["binding.proof_packet:blocks.remote_execution"],
        redaction_state: "safe",
      },
      visible_when: { mode: ["remote"] },
      data_testid: "remote-execution-lens",
    },
    {
      instance_id: "compare-lens",
      component_kind: "compare_lens",
      region: "rail",
      projection_binding: "binding.compare",
      visible_when: { mode: ["compare"], binding_missing_ok: "binding.compare" },
      data_testid: "compare-lens",
    },
    {
      instance_id: "inspector-selected-node",
      component_kind: "evidence_inspector",
      region: "rail",
      projection_binding: "binding.action_graph",
      visible_when: {
        mode: ["graph", "runway"],
        mode_not: ["proof", "remote", "compare"],
        selected_node: true,
      },
      data_testid: "evidence-inspector",
    },
    {
      instance_id: "operator",
      component_kind: "operator_command_bar",
      region: "operator",
      data_testid: "operator-chat",
    },
  ],
};

const BUNDLED_SPECS: Record<string, ViewSpec> = {
  "nlfr-default-v0": DEFAULT_VIEW_SPEC,
};

export function getBundledViewSpec(viewId: string): ViewSpec | null {
  return BUNDLED_SPECS[viewId] ?? null;
}
