"""Workspace configuration for ``nlfr init``."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import tomllib


NLFR_TOML = "nlfr.toml"
NLFR_DATA_MARKER = Path("data") / ".nlfr"
INIT_JSON = "init.json"
CONFIG_VERSION = 1


@dataclass(frozen=True)
class WorkspaceDefaults:
    """Resolved NLFR workspace defaults."""

    workspace: str
    output_dir: str
    database: str
    run_group: str

    def to_toml(self) -> str:
        return (
            "# Generated by nlfr init. Safe to commit or gitignore per team policy.\n"
            "[nlfr]\n"
            f"version = {CONFIG_VERSION}\n"
            "\n"
            "[nlfr.defaults]\n"
            f'workspace = "{self.workspace}"\n'
            f'output_dir = "{self.output_dir}"\n'
            f'database = "{self.database}"\n'
            f'run_group = "{self.run_group}"\n'
        )

    def to_init_json(self, *, force: bool) -> dict[str, object]:
        return {
            "version": CONFIG_VERSION,
            "initialized_at": _timestamp(),
            "force": force,
            "defaults": {
                "workspace": self.workspace,
                "output_dir": self.output_dir,
                "database": self.database,
                "run_group": self.run_group,
            },
        }


def default_workspace(cwd: Path) -> str:
    """Pick a sensible Bazel workspace path relative to ``cwd``.

    Used only by ``nlfr init`` (metadata scaffolding). ``init`` stays lenient —
    it falls back to ``.`` in a fresh directory rather than erroring — because
    it never invokes Bazel. The hard "no workspace found" error lives in
    :func:`resolve_workspace`, which the Bazel-invoking ``run``/``simulate``
    commands use.
    """

    demo_workspace = cwd / "demo" / "bazel-monorepo"
    if demo_workspace.is_dir():
        return "demo/bazel-monorepo"
    return "."


BAZEL_MARKERS = ("MODULE.bazel", "WORKSPACE", "WORKSPACE.bazel")

DEMO_WORKSPACE_NOTICE = (
    "nlfr: using bundled demo workspace demo/bazel-monorepo "
    "(pass --workspace for your own repo)"
)


class WorkspaceResolutionError(RuntimeError):
    """Raised when no Bazel workspace can be resolved and none was provided."""


def _package_root() -> Path:
    """Return the checkout root as seen from this module.

    ``src/nlfr/config.py`` -> ``parents[2]`` is the repository root when running
    from a source tree (editable install or ``PYTHONPATH=src``). For a wheel
    install this points into ``site-packages`` and the source-checkout heuristic
    below fails — which is the desired behaviour: adopters who ``pip install``
    NLFR never silently inherit the bundled demo workspace.
    """

    return Path(__file__).resolve().parents[2]


def source_checkout_root() -> Path | None:
    """Return the NLFR source-checkout root, or ``None`` when not a source tree.

    Heuristic: the root contains ``demo/bazel-monorepo`` AND a ``pyproject.toml``
    whose ``project.name`` is ``nativelink-agent-flight-recorder``.
    """

    root = _package_root()
    if not (root / "demo" / "bazel-monorepo").is_dir():
        return None
    pyproject = root / "pyproject.toml"
    if not pyproject.is_file():
        return None
    try:
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return None
    project = data.get("project")
    if not isinstance(project, dict):
        return None
    if project.get("name") != "nativelink-agent-flight-recorder":
        return None
    return root


def _is_within(path: Path, root: Path) -> bool:
    path = path.resolve()
    root = root.resolve()
    return path == root or root in path.parents


def is_within_source_checkout(path: Path) -> bool:
    """Return True when ``path`` lies inside the NLFR source checkout."""

    root = source_checkout_root()
    return root is not None and _is_within(path, root)


GITHUB_REPO_URL = "https://github.com/heyitsalec/nativelink-agent-flight-recorder"
GITHUB_BLOB_BASE = f"{GITHUB_REPO_URL}/blob/main"


def doc_url(repo_relative_path: str) -> str:
    """Return the canonical GitHub blob URL for a repo-relative path."""

    return f"{GITHUB_BLOB_BASE}/{repo_relative_path.strip('/')}"


def doc_hint(repo_relative_path: str) -> str:
    """Format a "read next" pointer that resolves for BOTH NLFR personas.

    Every CLI doc pointer must route through here (GitHub issue #39). A bare
    repo-relative path like ``docs/DEV_ENVIRONMENT.md`` is a dead end for the
    documented uvx/pip adopter who never cloned the repo, so this helper:

    * ALWAYS emits the canonical GitHub URL — the one pointer that resolves with
      no clone; and
    * additionally appends ``(local: <path>)`` only when the path exists as a
      file relative to the detected source checkout
      (:func:`source_checkout_root`), so an in-repo contributor also gets the
      on-disk pointer.

    It never returns a bare path as the sole (dead-end) pointer. Centralizing
    formatting here is what stops future hints from regressing to bare paths.
    """

    clean = repo_relative_path.strip("/")
    url = doc_url(clean)
    root = source_checkout_root()
    if root is not None and (root / clean).is_file():
        return f"{url} (local: {clean})"
    return url


def bazel_marker(cwd: Path) -> str | None:
    """Return the first Bazel workspace marker present in ``cwd``, else ``None``."""

    for marker in BAZEL_MARKERS:
        if (cwd / marker).is_file():
            return marker
    return None


def resolve_workspace(
    cwd: Path,
    explicit: str | None = None,
) -> tuple[Path, str | None]:
    """Resolve the Bazel workspace for ``run``/``simulate``.

    Precedence (explicit ``--workspace`` always wins):

    0. explicit path -> use it, no notice.
    a. ``cwd`` inside the NLFR source checkout -> bundled demo workspace, with a
       one-line stderr notice so in-repo/CI usage keeps working transparently.
    b. ``cwd`` contains a Bazel marker (MODULE.bazel / WORKSPACE / WORKSPACE.bazel)
       -> use ``cwd`` as the workspace, with a stderr notice.
    c. otherwise -> :class:`WorkspaceResolutionError` (caller exits 2, no trace).

    Returns ``(workspace_path, notice_or_None)``.
    """

    if explicit:
        return Path(explicit).resolve(), None

    cwd = cwd.resolve()
    src_root = source_checkout_root()
    if src_root is not None and _is_within(cwd, src_root):
        return (src_root / "demo" / "bazel-monorepo").resolve(), DEMO_WORKSPACE_NOTICE

    if bazel_marker(cwd) is not None:
        return cwd, f"nlfr: using workspace {cwd}"

    raise WorkspaceResolutionError(
        f"no Bazel workspace found in {cwd}; pass --workspace PATH"
    )


def nativelink_config_from_toml(cwd: Path) -> str | None:
    """Return a NativeLink config path declared in ``<cwd>/nlfr.toml``.

    Optional key ``[nlfr.defaults] nativelink_config = "path"``. ``doctor``
    consults this as the middle tier of its local-exec config precedence.
    Missing file/key -> ``None``.
    """

    config_path = cwd / NLFR_TOML
    if not config_path.is_file():
        return None
    try:
        payload = tomllib.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return None
    defaults = payload.get("nlfr", {}).get("defaults", {})
    if not isinstance(defaults, dict):
        return None
    value = defaults.get("nativelink_config")
    if isinstance(value, str) and value:
        return value
    return None


def resolve_defaults(
    cwd: Path,
    *,
    workspace: str | None = None,
    output_dir: str | None = None,
    database: str | None = None,
    run_group: str | None = None,
) -> WorkspaceDefaults:
    """Resolve init defaults using explicit overrides or workspace heuristics."""

    resolved_output = output_dir or "data/nlfr"
    return WorkspaceDefaults(
        workspace=workspace or default_workspace(cwd),
        output_dir=resolved_output,
        database=database or f"{resolved_output}/nlfr.sqlite",
        run_group=run_group or "latest",
    )


def load_defaults(cwd: Path) -> WorkspaceDefaults | None:
    """Load defaults from ``nlfr.toml`` when present."""

    config_path = cwd / NLFR_TOML
    if not config_path.exists():
        return None

    payload = tomllib.loads(config_path.read_text())
    defaults = payload.get("nlfr", {}).get("defaults", {})
    if not defaults:
        return None

    return WorkspaceDefaults(
        workspace=str(defaults.get("workspace", default_workspace(cwd))),
        output_dir=str(defaults.get("output_dir", "data/nlfr")),
        database=str(defaults.get("database", "data/nlfr/nlfr.sqlite")),
        run_group=str(defaults.get("run_group", "latest")),
    )


def scaffold_workspace(
    cwd: Path,
    defaults: WorkspaceDefaults,
    *,
    force: bool = False,
) -> dict[str, object]:
    """Create NLFR scaffold files and directories idempotently."""

    cwd = cwd.resolve()
    config_path = cwd / NLFR_TOML
    marker_dir = cwd / NLFR_DATA_MARKER
    output_dir = cwd / defaults.output_dir
    toml_body = defaults.to_toml()

    created: list[str] = []
    unchanged: list[str] = []

    marker_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not config_path.exists():
        config_path.write_text(toml_body)
        created.append(config_path.relative_to(cwd).as_posix())
    elif force or config_path.read_text() == toml_body:
        if force and config_path.read_text() != toml_body:
            config_path.write_text(toml_body)
            created.append(config_path.relative_to(cwd).as_posix())
        else:
            unchanged.append(config_path.relative_to(cwd).as_posix())
    else:
        unchanged.append(config_path.relative_to(cwd).as_posix())

    init_path = marker_dir / INIT_JSON
    if not init_path.exists():
        init_body = json.dumps(
            defaults.to_init_json(force=force),
            indent=2,
            sort_keys=True,
        ) + "\n"
        init_path.write_text(init_body)
        created.append(init_path.relative_to(cwd).as_posix())
    elif force:
        init_body = json.dumps(
            defaults.to_init_json(force=force),
            indent=2,
            sort_keys=True,
        ) + "\n"
        init_path.write_text(init_body)
        created.append(init_path.relative_to(cwd).as_posix())
    else:
        unchanged.append(init_path.relative_to(cwd).as_posix())

    return {
        "cwd": str(cwd),
        "defaults": {
            "workspace": defaults.workspace,
            "output_dir": defaults.output_dir,
            "database": defaults.database,
            "run_group": defaults.run_group,
        },
        "paths": {
            "config": config_path.relative_to(cwd).as_posix(),
            "marker_dir": marker_dir.relative_to(cwd).as_posix(),
            "output_dir": output_dir.relative_to(cwd).as_posix(),
            "database": defaults.database,
        },
        "created": created,
        "unchanged": unchanged,
        "idempotent": not created,
    }


def _timestamp() -> str:
    return datetime.now(UTC).isoformat(timespec="microseconds").replace("+00:00", "Z")
