"""Workspace configuration for ``nlfr init``."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import tomllib


NLFR_TOML = "nlfr.toml"
NLFR_DATA_MARKER = Path("data") / ".nlfr"
INIT_JSON = "init.json"
CONFIG_VERSION = 1


@dataclass(frozen=True)
class WorkspaceDefaults:
    """Resolved NLFR workspace defaults."""

    workspace: str
    output_dir: str
    database: str
    run_group: str

    def to_toml(self) -> str:
        return (
            "# Generated by nlfr init. Safe to commit or gitignore per team policy.\n"
            "[nlfr]\n"
            f"version = {CONFIG_VERSION}\n"
            "\n"
            "[nlfr.defaults]\n"
            f'workspace = "{self.workspace}"\n'
            f'output_dir = "{self.output_dir}"\n'
            f'database = "{self.database}"\n'
            f'run_group = "{self.run_group}"\n'
        )

    def to_init_json(self, *, force: bool) -> dict[str, object]:
        return {
            "version": CONFIG_VERSION,
            "initialized_at": _timestamp(),
            "force": force,
            "defaults": {
                "workspace": self.workspace,
                "output_dir": self.output_dir,
                "database": self.database,
                "run_group": self.run_group,
            },
        }


def default_workspace(cwd: Path) -> str:
    """Pick a sensible Bazel workspace path relative to ``cwd``."""

    demo_workspace = cwd / "demo" / "bazel-monorepo"
    if demo_workspace.is_dir():
        return "demo/bazel-monorepo"
    return "."


def resolve_defaults(
    cwd: Path,
    *,
    workspace: str | None = None,
    output_dir: str | None = None,
    database: str | None = None,
    run_group: str | None = None,
) -> WorkspaceDefaults:
    """Resolve init defaults using explicit overrides or workspace heuristics."""

    resolved_output = output_dir or "data/nlfr"
    return WorkspaceDefaults(
        workspace=workspace or default_workspace(cwd),
        output_dir=resolved_output,
        database=database or f"{resolved_output}/nlfr.sqlite",
        run_group=run_group or "latest",
    )


def load_defaults(cwd: Path) -> WorkspaceDefaults | None:
    """Load defaults from ``nlfr.toml`` when present."""

    config_path = cwd / NLFR_TOML
    if not config_path.exists():
        return None

    payload = tomllib.loads(config_path.read_text())
    defaults = payload.get("nlfr", {}).get("defaults", {})
    if not defaults:
        return None

    return WorkspaceDefaults(
        workspace=str(defaults.get("workspace", default_workspace(cwd))),
        output_dir=str(defaults.get("output_dir", "data/nlfr")),
        database=str(defaults.get("database", "data/nlfr/nlfr.sqlite")),
        run_group=str(defaults.get("run_group", "latest")),
    )


def scaffold_workspace(
    cwd: Path,
    defaults: WorkspaceDefaults,
    *,
    force: bool = False,
) -> dict[str, object]:
    """Create NLFR scaffold files and directories idempotently."""

    cwd = cwd.resolve()
    config_path = cwd / NLFR_TOML
    marker_dir = cwd / NLFR_DATA_MARKER
    output_dir = cwd / defaults.output_dir
    toml_body = defaults.to_toml()

    created: list[str] = []
    unchanged: list[str] = []

    marker_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not config_path.exists():
        config_path.write_text(toml_body)
        created.append(config_path.relative_to(cwd).as_posix())
    elif force or config_path.read_text() == toml_body:
        if force and config_path.read_text() != toml_body:
            config_path.write_text(toml_body)
            created.append(config_path.relative_to(cwd).as_posix())
        else:
            unchanged.append(config_path.relative_to(cwd).as_posix())
    else:
        unchanged.append(config_path.relative_to(cwd).as_posix())

    init_path = marker_dir / INIT_JSON
    if not init_path.exists():
        init_body = json.dumps(
            defaults.to_init_json(force=force),
            indent=2,
            sort_keys=True,
        ) + "\n"
        init_path.write_text(init_body)
        created.append(init_path.relative_to(cwd).as_posix())
    elif force:
        init_body = json.dumps(
            defaults.to_init_json(force=force),
            indent=2,
            sort_keys=True,
        ) + "\n"
        init_path.write_text(init_body)
        created.append(init_path.relative_to(cwd).as_posix())
    else:
        unchanged.append(init_path.relative_to(cwd).as_posix())

    return {
        "cwd": str(cwd),
        "defaults": {
            "workspace": defaults.workspace,
            "output_dir": defaults.output_dir,
            "database": defaults.database,
            "run_group": defaults.run_group,
        },
        "paths": {
            "config": config_path.relative_to(cwd).as_posix(),
            "marker_dir": marker_dir.relative_to(cwd).as_posix(),
            "output_dir": output_dir.relative_to(cwd).as_posix(),
            "database": defaults.database,
        },
        "created": created,
        "unchanged": unchanged,
        "idempotent": not created,
    }


def _timestamp() -> str:
    return datetime.now(UTC).isoformat(timespec="microseconds").replace("+00:00", "Z")
